### ISSUE TITLE
Add scope for oauth2 binding

### ISSUE THREAD

**Issue by voor** [spring-cloud/spring-cloud-bindings#59]
It would help if you added `scope` as an option: https://docs.spring.io/spring-security/site/docs/5.2.12.RELEASE/reference/html/oauth2.html#oauth2login-boot-property-mappings since that is commonly configured alongside the other variables included so far.

While you're there, some of the other ones that might be beneficial:

`spring.security.oauth2.client.registration.[registrationId].authorization-grant-type`
`spring.security.oauth2.client.registration.[registrationId].client-authentication-method`

**Comment by voor** [comment]
Okay, it's actually `scope` (singular) in the Spring Boot config.  So given a secret that looks like this:

```
apiVersion: v1
stringData:
  client-id: fake-client
  client-secret: a0c1eea6-6e5e-4de8-a0c8-832e328e35ae
  issuer-uri: https://127.0.0.1:8443
  provider: appsso
  scope: "[openid, profile, email]"
  type: oauth2
  authorization-grant-type: authorization_code
kind: Secret
metadata:
  name: sample-oauth2-secret
```

That should be bound into Spring boot like this:

```
  security:
    oauth2:
      client:
        registration:
          appsso:
            client-id: fake-client
            client-secret: a0c1eea6-6e5e-4de8-a0c8-832e328e35ae
            provider: appsso
            authorization-grant-type: authorization_code
            scope: ["openid", "profile", "email"]
        provider:
          appsso:
            issuer-uri: https://127.0.0.1:8443
```
